"""Generate OWL class axioms for Node damage/inventory/operation/other codes
from a CSV mapping file, and insert them into SDCO.rdf.

SDCO models each DIN EN 13508-2 damage code as an OWL class: owl:equivalentClass
matches the literal condition-report code (hasConditionCode hasValue "<code>"),
and rdfs:subClassOf carries a someValuesFrom restriction linking the code to its
taxonomy position. Characterization-letter subclasses add one more hasValue
restriction (on hasCharacterization1/2) via owl:intersectionOf. See DAA/DAA_A
and DAB/DAB1_A/DAB2_A in SDCO.rdf for the exact shapes this script reproduces.

The Node side of the taxonomy (NodeFabric/NodeInventory/NodeOperation/NodeOther)
is almost entirely unmodeled -- this script lets new codes be added in bulk via
node_codes.csv instead of hand-writing repetitive Turtle.

Each CSV row is one class: either a "base" row (a top-level code under one of
the 4 Node containers, parent_code left blank) or a "char" row (a
characterization-letter subclass of a base row, on dimension 1 or 2,
parent_code filled in). Rows whose class_name already exists in the ontology
are skipped (idempotent re-runs) but still count toward disjointness grouping
-- add a row for a pre-existing code (e.g. DAA) just to fold it into a
disjoint block alongside new siblings.

apply_defaults() fills in two fields when left blank, so the CSV only has to
carry the data that actually varies per row:
  - object_property: base rows default per category (CATEGORY_OBJECT_PROPERTY
    -- verified 100% consistent across every existing Pipe-side base class);
    char rows carry forward the property from an earlier row in the same
    (parent_code, characterization_dim) group, since that's also verified
    constant within a group -- only the first row of a group needs it spelled
    out.
  - class_name on char rows: derived as "<parent><dim>_<value>" if the code
    uses both characterization dimensions (per DAB1_A/DAB2_A), or plain
    "<parent>_<value>" if it only ever uses one (per DAA_A) -- checked against
    both this CSV batch and any already-declared siblings in the ontology.
An explicit value in the CSV always wins over these defaults.

Validation runs fully before anything is written: all errors are collected and
printed together, and the source file is left untouched if any are found.
filler_class values that don't exist yet only produce a warning (the user may
be about to create them by hand), but object_property values must already
exist in the ontology, UNLESS they match has(Node|Pipe)(Fabric|Operation)Damage
-- that narrow, regex-bounded case is auto-declared (mirroring the existing
hasPipeOperationDamage shape) since it's the one known gap (hasNodeOperationDamage).

Usage:
    python scripts/generate_node_codes.py --dry-run
    python scripts/generate_node_codes.py
"""

import argparse
import csv
import re
import sys
from pathlib import Path

from rdflib import OWL, RDF, RDFS, Graph, Namespace

REPO_ROOT = Path(__file__).resolve().parent.parent
NS = "https://l-jamora.github.io/sdco#"
M150_NS = "https://l-jamora.github.io/m150-onto#"
NODE = Namespace(NS)

NODE_CATEGORIES = {"NodeFabric", "NodeInventory", "NodeOperation", "NodeOther"}
AUTO_DECLARE_PATTERN = re.compile(r"^has(Node|Pipe)(Fabric|Operation)Damage$")

# Verified 100% consistent across every existing Pipe-side base class in SDCO.rdf
# (PipeFabric->hasPipeFabricDamage, PipeInventory->hasPipeInventoryFeature, etc.)
# -- safe to default a base row's object_property from its category alone.
CATEGORY_OBJECT_PROPERTY = {
    "NodeFabric": "hasNodeFabricDamage",
    "NodeInventory": "hasNodeInventoryFeature",
    "NodeOperation": "hasNodeOperationDamage",
    "NodeOther": "hasNodeFeature",
}
FOOTER_MARKER = (
    "###  Generated by the OWL API (version 4.5.29.2024-05-13T12:11:03Z) "
    "https://github.com/owlcs/owlapi"
)


def parse_any(path: Path) -> Graph:
    """Parse an ontology file whose serialization (turtle vs RDF/XML) may not match
    its .rdf extension -- some files in this project are Protege turtle exports
    saved with a .rdf extension, others are genuine RDF/XML."""
    g = Graph()
    try:
        g.parse(str(path), format="xml")
    except Exception:
        g = Graph()
        g.parse(str(path), format="turtle")
    return g


def read_rows(csv_path: Path) -> list[dict]:
    rows = []
    with open(csv_path, newline="", encoding="utf-8") as f:
        dialect = csv.Sniffer().sniff(f.readline(), delimiters=",;")
        f.seek(0)
        reader = csv.DictReader(f, dialect=dialect)
        fieldnames = reader.fieldnames or []
        first_col = fieldnames[0] if fieldnames else None
        for raw in reader:
            values = {k: (v or "").strip() for k, v in raw.items()}
            if not any(values.values()):
                continue  # blank line
            if first_col and values.get(first_col, "").startswith("#"):
                continue  # comment/TODO row
            rows.append(values)
    return rows


def _dims_present(parent: str, rows: list[dict], graph: Graph) -> set:
    """Which characterization dimensions ('1'/'2') this parent code uses, from
    this CSV batch plus any already-declared <parent>1_*/<parent>2_* siblings in
    the graph (covers codes whose other dimension was added in an earlier run)."""
    dims = {
        r["characterization_dim"]
        for r in rows
        if r.get("parent_code") == parent and r.get("characterization_dim") in ("1", "2")
    }
    for s in graph.subjects(RDF.type, OWL.Class):
        local = str(s).rsplit("#", 1)[-1]
        if local.startswith(parent + "1_"):
            dims.add("1")
        elif local.startswith(parent + "2_"):
            dims.add("2")
    return dims


def apply_defaults(rows: list[dict], graph: Graph) -> None:
    """Fill in class_name (char rows) and object_property (all rows) when left
    blank, using patterns verified against the existing ontology (see
    CATEGORY_OBJECT_PROPERTY and the naming rule in the design spec). Mutates
    rows in place; explicit values in the CSV always win over any default."""
    two_dim_cache: dict = {}
    last_prop_by_group: dict = {}

    for row in rows:
        parent = row.get("parent_code", "")
        if not parent:  # base row
            if not row.get("object_property"):
                row["object_property"] = CATEGORY_OBJECT_PROPERTY.get(row.get("category", ""), "")
            continue

        # char row
        if parent not in two_dim_cache:
            two_dim_cache[parent] = _dims_present(parent, rows, graph) == {"1", "2"}
        dim = row.get("characterization_dim", "")
        value = row.get("char_value", "")
        if not row.get("class_name") and dim and value:
            row["class_name"] = f"{parent}{dim}_{value}" if two_dim_cache[parent] else f"{parent}_{value}"

        group_key = (parent, dim)
        if row.get("object_property"):
            last_prop_by_group[group_key] = row["object_property"]
        elif group_key in last_prop_by_group:
            row["object_property"] = last_prop_by_group[group_key]


def _class_exists(graph: Graph, name: str) -> bool:
    return (NODE[name], RDF.type, OWL.Class) in graph


def _prop_exists(graph: Graph, name: str) -> bool:
    return (NODE[name], RDF.type, OWL.ObjectProperty) in graph


def _parent_resolves(parent: str, base_names: set, graph: Graph) -> bool:
    if parent in base_names:
        return True
    if not _class_exists(graph, parent):
        return False
    return any((NODE[parent], RDFS.subClassOf, NODE[cat]) in graph for cat in NODE_CATEGORIES)


def validate(rows: list[dict], graph: Graph) -> list[str]:
    errors = []
    seen_names = set()
    base_names = {r["class_name"] for r in rows if not r.get("parent_code")}

    for i, row in enumerate(rows, start=2):  # +2: header is line 1
        name = row.get("class_name", "")
        if not name:
            errors.append(f"row {i}: missing class_name (and it could not be auto-derived -- "
                          "check parent_code/characterization_dim/char_value are all filled in)")
            continue
        if name in seen_names:
            errors.append(f"row {i}: duplicate class_name '{name}'")
        seen_names.add(name)

        is_char = bool(row.get("parent_code"))

        if not is_char:
            category = row.get("category", "")
            if category not in NODE_CATEGORIES:
                errors.append(
                    f"row {i} ({name}): category '{category}' must be one of {sorted(NODE_CATEGORIES)}"
                )
        else:
            dim = row.get("characterization_dim", "")
            if dim not in ("1", "2"):
                errors.append(
                    f"row {i} ({name}): characterization_dim must be '1' or '2', got '{dim}'"
                )
            if not row.get("char_value"):
                errors.append(f"row {i} ({name}): char_value is required for row_type=char")
            parent = row.get("parent_code", "")
            if not parent:
                errors.append(f"row {i} ({name}): parent_code is required for row_type=char")
            elif not _parent_resolves(parent, base_names, graph):
                errors.append(
                    f"row {i} ({name}): parent_code '{parent}' does not resolve to an earlier "
                    f"'base' row in the CSV or an existing Node class in the ontology"
                )

        prop = row.get("object_property", "")
        if not prop:
            errors.append(f"row {i} ({name}): object_property is required")
        elif not _prop_exists(graph, prop) and not AUTO_DECLARE_PATTERN.match(prop):
            errors.append(
                f"row {i} ({name}): object_property ':{prop}' is not declared in the ontology "
                "and doesn't match the auto-declarable pattern has(Node|Pipe)(Fabric|Operation)Damage. "
                "Declare it manually first -- see :hasNodeFabricDamage or :hasPipeOperationDamage "
                "in SDCO.rdf for the shape to copy."
            )

        if not row.get("filler_class"):
            errors.append(f"row {i} ({name}): filler_class is required")

    return errors


def warn_missing_fillers(rows: list[dict], graph: Graph) -> None:
    for row in rows:
        filler = row.get("filler_class")
        if filler and not _class_exists(graph, filler):
            print(
                f"[warn] filler_class ':{filler}' referenced by '{row['class_name']}' does not "
                "exist yet in the ontology -- create it manually."
            )


def group_disjoints(rows: list[dict]) -> list[list[str]]:
    groups: dict = {}
    for row in rows:
        parent = row.get("parent_code", "")
        if not parent:
            key = ("base", row["category"])
        else:
            key = ("char", parent, row["characterization_dim"])
        groups.setdefault(key, []).append(row["class_name"])
    return [members for members in groups.values() if len(members) >= 2]


def _comment_clause(comment: str) -> str:
    if not comment:
        return ""
    escaped = comment.replace('"""', '\\"\\"\\"')
    return f' ;\n    rdfs:comment """{escaped}"""'


def render_property_decl(prop_name: str) -> str:
    family = AUTO_DECLARE_PATTERN.match(prop_name).group(1)  # "Node" or "Pipe"
    super_prop = f"has{family}Damage"
    return (
        f"###  {NS}{prop_name}\n"
        f":{prop_name} rdf:type owl:ObjectProperty , owl:AsymmetricProperty , owl:IrreflexiveProperty ;\n"
        f"    rdfs:subPropertyOf :{super_prop} .\n"
    )


def render_base_class(row: dict) -> str:
    name = row["class_name"]
    return (
        f"###  {NS}{name}\n"
        f":{name} rdf:type owl:Class ;\n"
        f"    owl:equivalentClass [ rdf:type owl:Restriction ;\n"
        f"                           owl:onProperty <{M150_NS}hasConditionCode> ;\n"
        f'                           owl:hasValue "{name}"\n'
        f"                         ] ;\n"
        f"    rdfs:subClassOf :{row['category']} ,\n"
        f"        [ rdf:type owl:Restriction ;\n"
        f"          owl:onProperty :{row['object_property']} ;\n"
        f"          owl:someValuesFrom :{row['filler_class']}\n"
        f"        ]{_comment_clause(row.get('comment', ''))} .\n"
    )


def render_char_class(row: dict) -> str:
    name = row["class_name"]
    parent = row["parent_code"]
    dim = row["characterization_dim"]
    return (
        f"###  {NS}{name}\n"
        f":{name} rdf:type owl:Class ;\n"
        f"    owl:equivalentClass [ owl:intersectionOf ( :{parent}\n"
        f"                                               [ rdf:type owl:Restriction ;\n"
        f"                                                 owl:onProperty <{M150_NS}hasCharacterization{dim}> ;\n"
        f'                                                 owl:hasValue "{row["char_value"]}"\n'
        f"                                               ]\n"
        f"                                             ) ;\n"
        f"                          rdf:type owl:Class\n"
        f"                        ] ;\n"
        f"    rdfs:subClassOf :{parent} ,\n"
        f"        [ rdf:type owl:Restriction ;\n"
        f"          owl:onProperty :{row['object_property']} ;\n"
        f"          owl:someValuesFrom :{row['filler_class']}\n"
        f"        ]{_comment_clause(row.get('comment', ''))} .\n"
    )


def render_disjoint_block(members: list[str]) -> str:
    members_str = " ".join(f":{m}" for m in members)
    return f"[ rdf:type owl:AllDisjointClasses ;\n  owl:members ( {members_str} )\n] .\n"


def build_output(rows: list[dict], graph: Graph) -> str:
    blocks = []

    declared_props: set = set()
    for row in rows:
        prop = row["object_property"]
        if prop in declared_props or _prop_exists(graph, prop):
            continue
        if AUTO_DECLARE_PATTERN.match(prop):
            blocks.append(render_property_decl(prop))
            declared_props.add(prop)

    for row in rows:
        if _class_exists(graph, row["class_name"]):
            continue  # idempotent skip -- already declared, still used for grouping below
        if row.get("parent_code"):
            blocks.append(render_char_class(row))
        else:
            blocks.append(render_base_class(row))

    for members in group_disjoints(rows):
        blocks.append(render_disjoint_block(members))

    return "\n\n".join(blocks)


def insert_before_footer(source_path: Path, new_text: str) -> None:
    text = source_path.read_text(encoding="utf-8")
    idx = text.rfind(FOOTER_MARKER)
    if idx == -1:
        print(f"[warn] footer marker not found in {source_path}; appending to end of file instead.")
        updated = text.rstrip("\n") + "\n\n\n" + new_text + "\n"
    else:
        before = text[:idx].rstrip("\n")
        after = text[idx:]
        updated = before + "\n\n\n" + new_text + "\n\n\n" + after
    source_path.write_text(updated, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--csv", default=str(REPO_ROOT / "scripts" / "node_codes.csv"), help="CSV mapping file to read.")
    parser.add_argument("--source", default=str(REPO_ROOT / "SDCO.rdf"), help="Ontology file to update.")
    parser.add_argument(
        "--dry-run", action="store_true", help="Validate and print generated Turtle; don't write --source."
    )
    args = parser.parse_args()

    source = Path(args.source)
    csv_path = Path(args.csv)

    graph = parse_any(source)
    rows = read_rows(csv_path)
    apply_defaults(rows, graph)

    errors = validate(rows, graph)
    if errors:
        print(f"[error] {len(errors)} validation error(s) -- nothing written:")
        for e in errors:
            print(f"  - {e}")
        return 1

    warn_missing_fillers(rows, graph)

    output_text = build_output(rows, graph)
    if not output_text.strip():
        print("[done] nothing new to generate -- every row already exists in the ontology.")
        return 0

    n_classes = output_text.count("###  ")
    n_disjoint = output_text.count("AllDisjointClasses")

    if args.dry_run:
        print("--- generated Turtle (dry run, nothing written) ---")
        print(output_text)
        print(f"[dry-run] {n_classes} class/property block(s), {n_disjoint} disjoint block(s)")
        return 0

    insert_before_footer(source, output_text)
    print(f"[done] wrote {n_classes} class/property block(s), {n_disjoint} disjoint block(s) to {source}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
