"""Materialize literal object-property triples from SDCO.rdf's someValuesFrom restrictions.

SDCO.rdf models damage codes via owl:equivalentClass (matching literal condition-report
codes) plus rdfs:subClassOf restrictions using owl:someValuesFrom on object properties.
someValuesFrom is an existential restriction: HermiT correctly classifies individuals into
the right damage-code classes, but never invents a concrete filler individual, so no literal
triple like ":ind :hasPipeFabricDamage :CrackFissure" is ever produced.

This script runs HermiT (via owlready2) to realize each individual's named damage-code
classes, then runs a SPARQL CONSTRUCT query that walks from those named classes through the
(already-asserted, untouched) someValuesFrom restrictions to emit literal triples -- keeping
only the most-specific filler per (individual, property) pair. Output goes to a separate
derived file; SDCO.rdf itself is never modified (checked via hash before/after).
"""

import argparse
import hashlib
import shutil
import sys
import tempfile
from pathlib import Path

from rdflib import RDF, Graph, Namespace, URIRef

REPO_ROOT = Path(__file__).resolve().parent.parent
SDCO = Namespace("http://www.semanticweb.org/jluis/ontologies/sdco#")

VERIFY_IND = SDCO["0_ConditionReport_001_1"]
VERIFY_EXPECTED_TYPE = SDCO["BAB1_B"]

CONSTRUCT_QUERY = """
PREFIX rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:  <http://www.w3.org/2002/07/owl#>

CONSTRUCT { ?ind ?prop ?filler . }
WHERE {
  ?ind a owl:NamedIndividual .
  ?ind rdf:type/rdfs:subClassOf* ?restr .
  ?restr a owl:Restriction ; owl:onProperty ?prop ; owl:someValuesFrom ?filler .

  FILTER NOT EXISTS {
    ?ind rdf:type/rdfs:subClassOf* ?restr2 .
    ?restr2 a owl:Restriction ; owl:onProperty ?prop ; owl:someValuesFrom ?filler2 .
    ?filler2 rdfs:subClassOf+ ?filler .
    FILTER (?filler2 != ?filler)
  }
}
"""

OUTPUT_HEADER = """@prefix : <http://www.semanticweb.org/jluis/ontologies/sdco#> .
@prefix rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix owl: <http://www.w3.org/2002/07/owl#> .

<http://www.semanticweb.org/jluis/ontologies/sdco/materialized>
    rdf:type owl:Ontology ;
    owl:imports <http://www.semanticweb.org/jluis/ontologies/sdco> ;
    rdfs:label "SDCO materialized object-property triples (DERIVED)" ;
    rdfs:comment "Auto-generated by scripts/materialize_object_properties.py from SDCO.rdf via HermiT (owlready2) + SPARQL CONSTRUCT. DO NOT HAND-EDIT -- regenerate with: python scripts/materialize_object_properties.py. Source: SDCO.rdf." .

"""


def sha256_of(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def convert_turtle_to_owlxml(src_ttl: Path, dst_owl: Path) -> None:
    g = Graph()
    g.parse(str(src_ttl), format="turtle")
    g.serialize(destination=str(dst_owl), format="xml")


def run_hermit(tmp_dir: Path, owl_filename: str):
    import owlready2

    owlready2.onto_path.append(str(tmp_dir))
    onto = owlready2.get_ontology(owl_filename).load()
    with onto:
        owlready2.sync_reasoner(infer_property_values=True)
    inconsistent = list(owlready2.default_world.inconsistent_classes())
    if inconsistent:
        raise RuntimeError(f"Ontology inconsistent after reasoning: {inconsistent}")
    return onto


def export_and_reload(onto, dst_owl: Path) -> Graph:
    onto.save(file=str(dst_owl), format="rdfxml")
    g = Graph()
    g.parse(str(dst_owl), format="xml")
    return g


def named_types_persisted(g: Graph) -> bool:
    return (VERIFY_IND, RDF.type, VERIFY_EXPECTED_TYPE) in g


def build_fallback_graph(onto, src_ttl: Path) -> Graph:
    import owlready2

    g = Graph()
    g.parse(str(src_ttl), format="turtle")

    for ind in onto.individuals():
        ind_uri = URIRef(ind.iri)
        for t in ind.INDIRECT_is_a:
            if isinstance(t, owlready2.Restriction):
                continue
            if isinstance(t, owlready2.ThingClass):
                g.add((ind_uri, RDF.type, URIRef(t.iri)))
    return g


def warn_functional_property_conflicts(triples, source_ttl: Path) -> None:
    src = Graph()
    src.parse(str(source_ttl), format="turtle")
    OWL_NS = Namespace("http://www.w3.org/2002/07/owl#")
    functional_props = {s for s in src.subjects(RDF.type, OWL_NS.FunctionalProperty)}

    by_ind_prop = {}
    for s, p, o in triples:
        if p in functional_props:
            by_ind_prop.setdefault((s, p), set()).add(o)

    for (ind, prop), fillers in by_ind_prop.items():
        if len(fillers) > 1:
            print(
                f"[warn] functional property {prop} has multiple fillers for {ind}: "
                f"{sorted(str(f) for f in fillers)}",
                file=sys.stderr,
            )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", default=str(REPO_ROOT / "SDCO.rdf"))
    parser.add_argument("--output", default=str(REPO_ROOT / "derived" / "SDCO_materialized.ttl"))
    parser.add_argument("--tmp-dir", default=None)
    parser.add_argument("--keep-tmp", action="store_true")
    parser.add_argument("--force-fallback", action="store_true")
    args = parser.parse_args()

    source = Path(args.source)
    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)

    hash_before = sha256_of(source)

    tmp_dir = Path(args.tmp_dir) if args.tmp_dir else Path(tempfile.mkdtemp(prefix="sdco_materialize_"))
    tmp_dir.mkdir(parents=True, exist_ok=True)

    try:
        owl_path = tmp_dir / "sdco.owl"
        convert_turtle_to_owlxml(source, owl_path)

        onto = run_hermit(tmp_dir, owl_path.name)

        reasoned_owl_path = tmp_dir / "sdco_reasoned.owl"
        reasoned_graph = export_and_reload(onto, reasoned_owl_path)

        use_fallback = args.force_fallback or not named_types_persisted(reasoned_graph)
        if use_fallback:
            print("[verify] path B (fallback: Python-synthesized named-class rdf:type triples)")
            work_graph = build_fallback_graph(onto, source)
        else:
            print("[verify] path A (reasoner-exported graph)")
            work_graph = reasoned_graph

        result = work_graph.query(CONSTRUCT_QUERY)
        triples = sorted(result, key=lambda t: (str(t[0]), str(t[1]), str(t[2])))

        warn_functional_property_conflicts(triples, source)

        out = Graph()
        out.bind("", SDCO)
        for s, p, o in triples:
            out.add((s, p, o))

        body = out.serialize(format="turtle")
        # Strip rdflib's own prefix header lines; we supply our own fixed header.
        body_lines = [
            line for line in body.splitlines() if not line.startswith("@prefix") and line.strip() != ""
        ]
        output.write_text(OUTPUT_HEADER + "\n".join(body_lines) + "\n", encoding="utf-8")

        print(f"[done] wrote {len(triples)} triples to {output}")
    finally:
        if not args.keep_tmp:
            shutil.rmtree(tmp_dir, ignore_errors=True)

    hash_after = sha256_of(source)
    if hash_after != hash_before:
        raise RuntimeError("SDCO.rdf was modified by this script -- this must never happen")

    return 0


if __name__ == "__main__":
    sys.exit(main())
